// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXtb-941mVMPpjmkyAE71gg7SiCrD0w4s',
    appId: '1:202350587450:web:83efb3117ff5c9e8d44f03',
    messagingSenderId: '202350587450',
    projectId: 'github-push-notification-df2ed',
    authDomain: 'github-push-notification-df2ed.firebaseapp.com',
    storageBucket: 'github-push-notification-df2ed.firebasestorage.app',
    measurementId: 'G-L5381X672N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqFCwTCg7N-VSxzMBzA5SEZBfGesYMys0',
    appId: '1:202350587450:android:6c47ca4c5335f6fed44f03',
    messagingSenderId: '202350587450',
    projectId: 'github-push-notification-df2ed',
    storageBucket: 'github-push-notification-df2ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3EnhT75xS8SKWENjE3f2r1YjtkPHILWw',
    appId: '1:202350587450:ios:844b55f2f00da2fcd44f03',
    messagingSenderId: '202350587450',
    projectId: 'github-push-notification-df2ed',
    storageBucket: 'github-push-notification-df2ed.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3EnhT75xS8SKWENjE3f2r1YjtkPHILWw',
    appId: '1:202350587450:ios:844b55f2f00da2fcd44f03',
    messagingSenderId: '202350587450',
    projectId: 'github-push-notification-df2ed',
    storageBucket: 'github-push-notification-df2ed.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXtb-941mVMPpjmkyAE71gg7SiCrD0w4s',
    appId: '1:202350587450:web:69889a15fbc02d98d44f03',
    messagingSenderId: '202350587450',
    projectId: 'github-push-notification-df2ed',
    authDomain: 'github-push-notification-df2ed.firebaseapp.com',
    storageBucket: 'github-push-notification-df2ed.firebasestorage.app',
    measurementId: 'G-5L2PY5XVF2',
  );
}
